package com.example.data.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Ignore
import androidx.room.PrimaryKey
import com.example.model.GameItem

/**
 * Room database Entity named 'Game' representing a game saved in the user's library.
 * Contains fields for id, title, platform, iconPath, and packageName.
 */
@Entity(tableName = "games")
data class Game(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long = 0L,

    @ColumnInfo(name = "title")
    val title: String,

    @ColumnInfo(name = "platform")
    val platform: String,

    @ColumnInfo(name = "icon_path")
    val iconPath: String? = null,

    @ColumnInfo(name = "package_name")
    val packageName: String? = null
) {
    /**
     * Secondary constructor allowing integer IDs.
     */
    @Ignore
    constructor(
        id: Int,
        title: String,
        platform: String,
        iconPath: String? = null,
        packageName: String? = null
    ) : this(id.toLong(), title, platform, iconPath, packageName)

    /**
     * Secondary constructor for inserting games where ID is auto-generated by Room.
     */
    @Ignore
    constructor(
        title: String,
        platform: String,
        iconPath: String? = null,
        packageName: String? = null
    ) : this(0L, title, platform, iconPath, packageName)

    /**
     * Secondary constructor supporting string IDs.
     */
    @Ignore
    constructor(
        id: String,
        title: String,
        platform: String,
        iconPath: String? = null,
        packageName: String? = null
    ) : this(id.toLongOrNull() ?: 0L, title, platform, iconPath, packageName)

    /**
     * Convert Room entity to Presentation GameItem.
     */
    fun toGameItem(): GameItem {
        val iconResId = iconPath?.toIntOrNull() ?: 0
        val customUri = if (iconResId == 0) iconPath else null
        return GameItem(
            id = id.toString(),
            title = title,
            subtitle = "$platform Game",
            platform = platform,
            iconRes = iconResId,
            customIconUri = customUri,
            packageName = packageName
        )
    }

    companion object {
        fun fromGameItem(item: GameItem): Game {
            val iconVal = item.customIconUri ?: (if (item.iconRes != 0) item.iconRes.toString() else null)
            return Game(
                id = item.id.toLongOrNull() ?: 0L,
                title = item.title,
                platform = item.platform,
                iconPath = iconVal,
                packageName = item.packageName
            )
        }
    }
}
